# This file created by conda-build 25.11.1
# ------------------------------------------------

package:
  name: libmpdec
  version: 4.0.0
source:
  url: https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4.0.0.tar.gz
  sha256: 942445c3245b22730fd41a67a7c5c231d11cb1b9936b9c0f76334fb7d0b4468c
  patches:
    - fix-dll-name.diff
    - fix-win-arm64-config.diff
build:
  number: '1'
  noarch: false
  noarch_python: false
  python_version_independent: false
  string: hfd05255_1
requirements:
  build:
    - vs2022_win-64 19.44.35207 ha74f236_34
    - vs_win-64 2022.14 ha74f236_34
    - vswhere 3.1.7 h40126e0_1
  host:
    - ucrt 10.0.26100.0 h57928b3_0
    - vc 14.3 h41ae7f8_34
    - vc14_runtime 14.44.35208 h818238b_34
    - vcomp14 14.44.35208 h818238b_34
  run:
    - ucrt >=10.0.20348.0
    - vc >=14.3,<15
    - vc14_runtime >=14.44.35208
test:
  commands:
    - if not exist %LIBRARY_BIN%\libmpdec-4.dll exit 1
about:
  home: https://www.bytereef.org/mpdecimal/index.html
  summary: A package for correctly-rounded arbitrary precision decimal floating point
    arithmetic
  license: BSD-2-Clause
  license_file: COPYRIGHT.txt
extra:
  recipe-maintainers:
    - isuruf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260126.4.1
  remote_url: https://github.com/conda-forge/mpdecimal-feedstock
  sha: fc3e04b6c42fdd6fefe944e7fae9865240838c56
