# This file created by conda-build 26.1.0
# meta.yaml template originally from:
# C:\Users\task_177400101425808\rasterio-feedstock\recipe, last modified Fri Mar 20 10:14:21 2026
# ------------------------------------------------

package:
  name: rasterio
  version: 1.5.0
source:
  url: https://github.com/mapbox/rasterio/archive/1.5.0.tar.gz
  sha256: f5d5cab866545e85a21b1921458ee8c711e23489ccc44fa66c6f70443a3ecae6
build:
  number: '0'
  entry_points:
    - rio = rasterio.rio.main:main_group
  string: py312h0299d0f_0
requirements:
  build:
    - blas 1.0 mkl
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.12.2 haa95532_0
    - intel-openmp 2025.0.0 haa95532_1164
    - libexpat 2.7.4 hd7fb8db_0
    - libffi 3.4.4 hd77b12b_1
    - libhwloc 2.12.1 default_hfa10c62_1000
    - libiconv 1.18 hc89ec93_0
    - libmpdec 4.0.0 h827c3e9_0
    - libxml2 2.13.9 h6201b9f_0
    - libzlib 1.3.1 h02ab6af_0
    - lz4-c 1.9.4 h2bbff1b_1
    - mkl 2025.0.0 h5da7b33_930
    - mkl-service 2.5.2 py314h0b37514_0
    - mkl_fft 2.1.1 py314h281c9fe_0
    - mkl_random 1.3.0 py314hdbada53_0
    - numpy 2.4.2 py314hbda910b_0
    - numpy-base 2.4.2 py314h11a47e0_0
    - openssl 3.5.5 hbb43b14_0
    - python 3.14.3 h653fc63_101_cp314
    - python_abi 3.14 2_cp314
    - sqlite 3.51.2 hee5a0db_0
    - tbb 2022.3.0 h90c84d6_0
    - tbb-devel 2022.3.0 h90c84d6_0
    - tk 8.6.15 hf199647_0
    - tzdata 2026a he532380_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - vs2022_win-64 19.44.35207 hc920ad0_10
    - vs_win-64 2022.14 hc920ad0_10
    - vswhere 3.1.7 haa95532_0
    - xz 5.8.2 h53af0af_0
    - zlib 1.3.1 h02ab6af_0
    - zstd 1.5.7 h56299aa_0
  host:
    - blas 1.0 mkl
    - blosc 1.21.6 h4190f5b_0
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2025.12.2 haa95532_0
    - cython 3.1.4 py312h02ab6af_0
    - expat 2.7.4 hd7fb8db_0
    - freeglut 3.8.0 hfcef157_0
    - freexl 2.0.0 hd7a5696_0
    - geos 3.10.6 he74ecf9_0
    - geotiff 1.7.4 hfa75976_0
    - intel-openmp 2025.0.0 haa95532_1164
    - jpeg 9f ha349fce_0
    - lerc 4.0.0 h5da7b33_0
    - libarchive 3.8.2 h6c023e8_0
    - libbrotlicommon 1.2.0 h907acca_0
    - libbrotlidec 1.2.0 h02c67a5_0
    - libbrotlienc 1.2.0 h483e6b9_0
    - libcurl 8.18.0 he215731_0
    - libdeflate 1.22 h5bf469e_0
    - libexpat 2.7.4 hd7fb8db_0
    - libffi 3.4.4 hd77b12b_1
    - libgdal-core 3.11.4 h9745f9a_1
    - libhwloc 2.12.1 default_hfa10c62_1000
    - libiconv 1.18 hc89ec93_0
    - libkml 1.3.0 h63940dd_7
    - libkrb5 1.22.1 hb237eb7_0
    - libpng 1.6.55 h2854ad3_0
    - libspatialite 5.1.0 hc42ffd2_3
    - libssh2 1.11.1 h2addb87_0
    - libtiff 4.7.1 h3a18249_0
    - libwebp-base 1.6.0 hbf3958f_0
    - libxml2 2.13.9 h6201b9f_0
    - libzlib 1.3.1 h02ab6af_0
    - lz4-c 1.9.4 h2bbff1b_1
    - minizip 4.0.3 hb68bac4_0
    - mkl 2025.0.0 h5da7b33_930
    - mkl-service 2.5.2 py312h0b37514_0
    - mkl_fft 2.1.1 py312h300f80d_0
    - mkl_random 1.3.0 py312ha5e6156_0
    - numpy 2.1.3 py312h12f7302_3
    - numpy-base 2.1.3 py312he4e2855_3
    - openssl 3.5.5 hbb43b14_0
    - packaging 25.0 py312haa95532_1
    - pcre2 10.46 h5740b90_0
    - pip 26.0.1 pyhc872135_0
    - proj 9.7.1 hb43cae5_0
    - python 3.12.13 h63b1a2d_1
    - setuptools 80.10.2 py312haa95532_0
    - sqlite 3.51.2 hee5a0db_0
    - tbb 2022.3.0 h90c84d6_0
    - tbb-devel 2022.3.0 h90c84d6_0
    - tk 8.6.15 hf199647_0
    - tzdata 2026a he532380_0
    - ucrt 10.0.22621.0 haa95532_0
    - uriparser 0.9.8 h1a0bd13_0
    - vc 14.42 haa95532_5
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - wheel 0.46.3 py312haa95532_0
    - xerces-c 3.3.0 h885b0b7_0
    - xz 5.8.2 h53af0af_0
    - zlib 1.3.1 h02ab6af_0
    - zstd 1.5.7 h56299aa_0
  run:
    - affine
    - attrs
    - certifi
    - click >=4,!=8.2.*
    - cligj >=0.5
    - libgdal-core >=3.11.4,<3.12.0a0
    - libgdal-core >=3.8
    - numpy >=1.21,<3
    - proj >=9.7.1,<9.7.2.0a0
    - pyparsing
    - python >=3.12,<3.13.0a0
    - ucrt >=10.0.20348.0
    - vc >=14.3,<15
    - vc14_runtime >=14.44.35208
  run_constrained:
    - boto3 >=1.2.4
test:
  source_files:
    - tests
  imports:
    - rasterio
    - rasterio.abc
    - rasterio.control
    - rasterio.coords
    - rasterio.crs
    - rasterio.drivers
    - rasterio.dtypes
    - rasterio.enums
    - rasterio.env
    - rasterio.errors
    - rasterio.features
    - rasterio.fill
    - rasterio.io
    - rasterio.mask
    - rasterio.merge
    - rasterio.plot
    - rasterio.profiles
    - rasterio.rio
    - rasterio.rpc
    - rasterio.session
    - rasterio.shutil
    - rasterio.stack
    - rasterio.transform
    - rasterio.vrt
    - rasterio.warp
    - rasterio.windows
  requires:
    - aiohttp
    - boto3 >=1.2.4
    - fsspec
    - hypothesis
    - ipython >=2.0
    - libgdal-netcdf
    - matplotlib-base
    - packaging
    - pip
    - pytest >=2.8.2,<8
    - pytest-cov >=2.2.0
    - requests
    - shapely
  files:
    - test_data/test.tif
  commands:
    - pip check
    - rio --help
    - rio info test_data\\test.tif
about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: 'Rasterio reads and writes these formats and provides a Python API
    based on N-D arrays.

    '
  summary: Rasterio reads and writes geospatial raster datasets
  dev_url: https://github.com/mapbox/rasterio
  doc_url: https://rasterio.readthedocs.io
extra:
  recipe-maintainers:
    - ceholden
    - ocefpaf
    - snowman2
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/rasterio-feedstock
  sha: 6111d0965cacfd4c9e9a734d3ae26a5e197bf1ca
  task_id: QKvRDeMHS02gLxymllTZww
  task_run_id: '0'
  pbp_graph_uuid: a3eb3156-2026-4963-8cde-a5e9eab06c45
