# This file created by conda-build 24.11.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Mon Dec  9 10:39:48 2024
# ------------------------------------------------

package:
  name: lz4-c
  version: 1.10.0
source:
  sha256: 537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b
  url: https://github.com/lz4/lz4/archive/v1.10.0.tar.gz
build:
  number: '1'
  run_exports:
    - lz4-c >=1.10.0,<1.11.0a0
  string: h2466b09_1
requirements:
  build:
    - bzip2 1.0.8 h2466b09_7
    - ca-certificates 2024.8.30 h56e8100_0
    - cmake 3.31.2 h400e5d1_0
    - krb5 1.21.3 hdf4eb48_0
    - libcurl 8.10.1 h1ee3ff0_0
    - libexpat 2.6.4 he0c23c2_0
    - liblzma 5.6.3 h2466b09_1
    - libssh2 1.11.1 he619c9f_0
    - libuv 1.49.2 h2466b09_0
    - libzlib 1.3.1 h2466b09_2
    - ninja 1.12.1 hc790b64_0
    - openssl 3.4.0 h2466b09_0
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 ha32ba9b_23
    - vc14_runtime 14.42.34433 he29a5d6_23
    - vs2019_win-64 19.29.30139 he1865b1_23
    - vs_win-64 2019.11 he1865b1_23
    - vswhere 3.1.7 h57928b3_0
    - zstd 1.5.6 h0ea2cb4_0
  host:
    - ucrt 10.0.22621.0 h57928b3_1
    - vc 14.3 ha32ba9b_23
    - vc14_runtime 14.42.34433 he29a5d6_23
  run:
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
about:
  description: 'LZ4 is lossless compression algorithm, providing compression speed
    at 400

    MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,

    with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression

    derivative, called LZ4_HC, is available, trading customizable CPU time for

    compression ratio. LZ4 library is provided as open source software using a

    BSD license.

    '
  dev_url: https://github.com/lz4/lz4
  home: https://www.lz4.org
  license: BSD-2-Clause
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20241209.2.1
  recipe-maintainers:
    - mingwandroid
    - rmax
    - wesm
    - xhochy
  remote_url: https://github.com/conda-forge/lz4-c-feedstock
  sha: 1771aeaed9cf4d91619cee1e822416b03e429f54
