# This file created by conda-build 26.3.0
# meta.yaml template originally from:
# C:\Users\task_177697110847335\certifi-feedstock\recipe, last modified Thu Apr 23 19:06:11 2026
# ------------------------------------------------

package:
  name: certifi
  version: 2026.4.22
source:
  - url: https://github.com/certifi/python-certifi/archive/refs/tags/2026.04.22.tar.gz
    sha256: b0d792990086c46a5884cf011957c3a01f9139af199eb9f4f7a3c5db228b0edb
    folder: certifi
  - url: https://pypi.org/packages/py3/p/pip/pip-25.0.1-py3-none-any.whl
    sha256: c46efd13b6aa8279f33f2864459c8ce587ea6a1a59ee20de055868d8f7688f7f
    folder: boostrap_wheels
  - url: https://pypi.org/packages/py3/s/setuptools/setuptools-75.8.0-py3-none-any.whl
    sha256: e3982f444617239225d675215d51f6ba05f845d4eec313da4418fdbb56fb27e3
    folder: boostrap_wheels
  - url: https://pypi.org/packages/py3/w/wheel/wheel-0.45.1-py3-none-any.whl
    sha256: 708e7481cc80179af0e556bbf0cc00b8444c7321e2700b8d8580231d13017248
    folder: boostrap_wheels
build:
  number: '0'
  script_env:
    - PYTHONPATH=C:\Users\task_177697110847335\croot\certifi_1776971221683\work\boostrap_wheels;
  script:
    - cd certifi
    - C:\\Users\\task_177697110847335\\croot\\certifi_1776971221683\\_h_env\\python.exe
      -m pip install . --ignore-installed --no-deps --no-build-isolation -vv
  string: py312haa95532_0
requirements:
  host:
    - bzip2 1.0.8 h2bbff1b_6
    - ca-certificates 2026.3.19 haa95532_0
    - libexpat 2.7.5 hd7fb8db_0
    - libffi 3.4.4 hd77b12b_1
    - libzlib 1.3.1 h02ab6af_0
    - openssl 3.5.6 hbb43b14_0
    - python 3.12.13 h63b1a2d_1
    - sqlite 3.51.2 hee5a0db_0
    - tk 8.6.15 hf199647_0
    - tzdata 2026a he532380_0
    - ucrt 10.0.22621.0 haa95532_0
    - vc 14.3 h2df5915_10
    - vc14_runtime 14.44.35208 h4927774_10
    - vs2015_runtime 14.44.35208 ha6b5a95_10
    - xz 5.8.2 h53af0af_0
    - zlib 1.3.1 h02ab6af_0
  run:
    - python >=3.12,<3.13.0a0
test:
  source_files:
    - certifi/certifi/tests
  imports:
    - certifi
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('certifi')=='2026.4.22')"
    - pytest -vv certifi/certifi/tests
about:
  home: https://certifi.io
  license: MPL-2.0
  license_file: certifi/LICENSE
  license_family: Other
  summary: Python package for providing Mozilla's CA Bundle.
  description: 'Certifi is a curated collection of Root Certificates for validating
    the

    trustworthiness of SSL certificates while verifying the identity of TLS

    hosts.

    '
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  dev_url: https://github.com/certifi/python-certifi
extra:
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
    - sigmavirus24
  skip-lints:
    - missing_python_build_tool
  final: true
  copy_test_source_files: true
  remote_url: https://github.com/AnacondaRecipes/certifi-feedstock
  sha: 0bb6b6707f8d88aabb9eb9cb65e12ceef0647660
  task_id: fq3EFuZZRK29TioT1Zi-Tg
  task_run_id: '0'
  pbp_graph_uuid: 4a276af2-d5d9-4f18-bc19-58410d75d4cd
