# This file created by conda-build 25.3.2
# ------------------------------------------------

package:
  name: vc
  version: '14.42'
build:
  number: 5
  string: haa95532_5
  track_features:
    - vc14
requirements:
  build: []
  run:
    - vs2015_runtime >=14.42.34433
about:
  description: 'This metapackage is used to enforce consistency of runtime

    dependencies within an environment

    '
  dev_url: https://github.com/conda/conda/wiki/VC-features
  doc_url: https://github.com/conda/conda/wiki/VC-features
  home: https://github.com/conda/conda/wiki/VC-features
  license: BSD-3-Clause
  license_family: BSD
  license_file: C:\b\abs_a5gfp95sae\clone\recipe/LICENSE
  summary: A meta-package to impose mutual exclusivity among software built with different
    VS versions
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a50a1607-7afb-403d-9506-0da285991ce9
  remote_url: git@github.com:AnacondaRecipes/vs2022-feedstock.git
  sha: 176852ecb3355c67e7f98ee392f1281e723140ff
